version: "3.7"
services:
  db_dbt_mysql:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    container_name: grai-jaffle-test-mysql
    restart: unless-stopped
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=db
      - MYSQL_USER=docker
      - MYSQL_PASSWORD=docker
      - MYSQL_ROOT_PASSWORD=docker
  server:
    image: ghcr.io/grai-io/grai-core/grai-server:latest
    ports:
      - 8000:8000
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=docker
      - DB_USER=docker
      - DB_PASSWORD=docker
      - DJANGO_SUPERUSER_USERNAME=null@grai.io
      - DJANGO_SUPERUSER_PASSWORD=super_secret
    depends_on: 
      - db
  db:
    image: postgres:14.3-alpine
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=docker
    ports:
      - 5432:5432
    healthcheck:
      test: "pg_isready -U docker"
      interval: 2s
      timeout: 2s
      retries: 15
  frontend_mysql:
    image: ghcr.io/grai-io/grai-core/grai-frontend:latest
    ports:
      - 3000:80